# Generated by Django 5.2.5 on 2025-09-16 17:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=150, verbose_name="Заголовок")),
                ("body", models.TextField(verbose_name="Содержание")),
                ("image", models.ImageField(blank=True, upload_to="photos/blog/", verbose_name="Фотография")),
                (
                    "publish_at",
                    models.DateTimeField(default=django.utils.timezone.now, verbose_name="Дата публикации"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")),
                ("update_at", models.DateTimeField(auto_now=True, verbose_name="Последнее обновление")),
                (
                    "status",
                    models.CharField(
                        choices=[("DR", "Draft"), ("PB", "Published")],
                        default="DR",
                        max_length=2,
                        verbose_name="Статус",
                    ),
                ),
                ("views_count", models.PositiveIntegerField(default=0, verbose_name="Количество просмотров")),
            ],
            options={
                "verbose_name": "пост",
                "verbose_name_plural": "посты",
                "ordering": ["publish_at"],
                "indexes": [models.Index(fields=["publish_at"], name="blog_post_publish_6c210a_idx")],
            },
        ),
    ]
