# Generated by Django 5.2.5 on 2025-09-16 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="update_at",
            new_name="updated_at",
        ),
    ]
