# Generated by Django 5.2.6 on 2025-09-17 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_rename_update_at_post_updated_at"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={"ordering": ["-publish_at"], "verbose_name": "пост", "verbose_name_plural": "посты"},
        ),
        migrations.RemoveIndex(
            model_name="post",
            name="blog_post_publish_6c210a_idx",
        ),
        migrations.AddField(
            model_name="post",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Статус публикации"),
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(fields=["-publish_at"], name="blog_post_publish_bc5a66_idx"),
        ),
    ]
