# Generated by Django 5.2.5 on 2025-10-13 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_alter_product_options_product_owner_product_status"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ["-created_at"],
                "permissions": [
                    ("can_unpublish_product", "Can unpublish product"),
                    ("can_publish_product", "Can publish product"),
                ],
                "verbose_name": "продукт",
                "verbose_name_plural": "продукты",
            },
        ),
    ]
